# syntax=docker/dockerfile:1.8@sha256:d6d396f3780b1dd56a3acbc975f57bd2fc501989b50164c41387c42d04e780d0

# Dockerfile for building GRASS GIS on AlmaLinux 9 (conda-forge base)

ARG GUI=without

FROM quay.io/condaforge/linux-anvil-x86_64:alma9 as common_start

LABEL authors="Carmen Tawalika,Markus Neteler,Anika Weinmann,Stefan Blumentrath"
LABEL maintainer="tawalika@mundialis.de,neteler@mundialis.de,weinmann@mundialis.de"

SHELL ["/bin/bash", "-c"]

WORKDIR /tmp

ARG GUI

# GRASS GIS runtime packages for AlmaLinux/RHEL
ARG GRASS_RUN_PACKAGES="gcc \
    gcc-c++ \
    make \
    bison \
    flex \
    bzip2 \
    git \
    glibc-langpack-en \
    cairo \
    fftw \
    fftw-devel \
    freetype \
    gdal \
    gdal-devel \
    geos \
    geos-devel \
    proj \
    proj-devel \
    netcdf \
    netcdf-devel \
    file \
    file-libs \
    libjpeg-turbo \
    jsoncpp-devel \
    ncurses \
    ncurses-devel \
    openblas \
    openblas-devel \
    openjpeg2 \
    libomp \
    libomp-devel \
    postgresql-devel \
    gsl \
    gsl-devel \
    libpng \
    libpng-devel \
    postgresql-libs \
    python3 \
    python3-devel \
    readline \
    readline-devel \
    sqlite \
    sqlite-devel \
    libtiff \
    libtiff-tools \
    libzstd \
    libzstd-devel \
    unzip \
    wget \
    vim \
    zip \
    zlib \
    zlib-devel \
    "
ENV GRASS_RUN_PACKAGES=${GRASS_RUN_PACKAGES}

# Define build packages
ARG GRASS_BUILD_PACKAGES="cmake \
    bzip2-devel \
    cairo-devel \
    freetype-devel \
    libjpeg-turbo-devel \
    libtiff-devel \
    mesa-libGL-devel \
    mesa-libGLU-devel \
    "
ENV GRASS_BUILD_PACKAGES=${GRASS_BUILD_PACKAGES}

ARG GRASS_CONFIG="--with-cxx \
  --enable-largefile \
  --with-proj-share=/usr/share/proj \
  --with-gdal=/usr/bin/gdal-config \
  --with-geos \
  --with-sqlite \
  --with-cairo --with-cairo-ldflags=-lfontconfig \
  --with-freetype --with-freetype-includes=/usr/include/freetype2/ \
  --with-fftw \
  --with-postgres --with-postgres-includes=/usr/include \
  --with-netcdf \
  --with-zstd \
  --with-bzlib \
    --with-pdal \
  --without-mysql \
  --with-blas \
  --with-lapack \
  --with-readline \
  --with-odbc \
  --with-openmp \
  "

ARG GRASS_PYTHON_PACKAGES="pip \
    setuptools \
    python-dateutil \
    python-magic \
    numpy \
    Pillow \
    ply \
    matplotlib \
    psycopg2-binary \
  "
ENV GRASS_PYTHON_PACKAGES=${GRASS_PYTHON_PACKAGES}


FROM common_start as grass_without_gui

ARG GRASS_CONFIG="${GRASS_CONFIG} --without-opengl"
ENV GRASS_CONFIG=${GRASS_CONFIG}

FROM common_start as grass_with_gui

ARG GRASS_RUN_PACKAGES="${GRASS_RUN_PACKAGES} \
  adwaita-icon-theme \
  mesa-libGL \
  mesa-libGLU \
  gtk3 \
  libnotify \
  SDL2 \
  libXtst \
  librsvg2 \
  gettext \
  freeglut \
  gstreamer1-plugins-base \
  libSM \
  webkit2gtk3 \
"

ARG GRASS_BUILD_PACKAGES="${GRASS_BUILD_PACKAGES} \
  gtk3-devel \
  libnotify-devel \
  SDL2-devel \
  libXtst-devel \
  freeglut-devel \
  gstreamer1-plugins-base-devel \
  libSM-devel \
  webkit2gtk3-devel \
"

ARG GRASS_CONFIG="${GRASS_CONFIG} --with-opengl \
  --with-x \
  --with-nls \
  --with-readline \
  "
ARG GRASS_PYTHON_PACKAGES="${GRASS_PYTHON_PACKAGES} wxPython"
# If you do not use any Gnome Accessibility features, to suppress warning
# WARNING **: Couldn't connect to accessibility bus:
# execute programs with
ENV NO_AT_BRIDGE=1


FROM grass_${GUI}_gui as grass_gis

# Install EPEL repository for additional packages
RUN dnf install -y epel-release \
    && dnf config-manager --set-enabled crb \
    && dnf makecache

# Install runtime packages
RUN dnf install -y --allowerasing --setopt=install_weak_deps=False \
    $GRASS_RUN_PACKAGES \
    && dnf clean all \
    && rm -rf /var/cache/dnf/*

# Set up locale
RUN dnf install -y glibc-locale-source glibc-langpack-en \
    && localedef -i en_US -f UTF-8 en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

## fetch vertical datums for PDAL and store into PROJ dir
WORKDIR /src

# Start build stage
FROM grass_gis as build

# Add build packages
RUN dnf install -y --setopt=install_weak_deps=False \
    $GRASS_BUILD_PACKAGES \
    && dnf clean all \
    && rm -rf /var/cache/dnf/*

# Add pip and Python packages
RUN (echo "Install Python packages" \
    && python3 -m ensurepip --upgrade \
    && python3 -m pip install --upgrade pip \
    && mkdir -p /src/site-packages \
    && cd /src \
    && python3 -m pip install --no-cache-dir -t /src/site-packages --upgrade \
    $GRASS_PYTHON_PACKAGES \
    && rm -rf /root/.cache \
    && rm -rf /tmp/pip-* \
    )

# Download and extract GRASS GIS source code from GitHub
RUN wget https://github.com/OSGeo/grass/archive/refs/tags/8.4.1.tar.gz \
    && tar -xzf 8.4.1.tar.gz \
    && mv grass-8.4.1 /src/grass_build \
    && rm 8.4.1.tar.gz

WORKDIR /src/grass_build

# Set environmental variables for GRASS GIS compilation, without debug symbols
# Set gcc/g++ environmental variables for GRASS GIS compilation, without debug symbols
ENV MYCFLAGS "-O2 -std=gnu99 -m64"
ENV MYLDFLAGS "-s"
# CXX stuff:
ENV LD_LIBRARY_PATH "/usr/local/lib"
ENV LDFLAGS "$MYLDFLAGS"
ENV CFLAGS "$MYCFLAGS"
ENV CXXFLAGS "$MYCXXFLAGS"

# Configure compile and install GRASS GIS
ENV NUMTHREADS=4
RUN make distclean || echo "nothing to clean"
RUN ./configure $GRASS_CONFIG \
    && make -j $NUMTHREADS \
    && make install && ldconfig \
    &&  cp /usr/local/grass84/gui/wxpython/xml/module_items.xml module_items.xml; \
    rm -rf /usr/local/grass84/demolocation; \
    rm -rf /usr/local/grass84/fonts; \
    rm -rf /usr/local/grass84/gui; \
    rm -rf /usr/local/grass84/share; \
    mkdir -p /usr/local/grass84/gui/wxpython/xml/; \
    mv module_items.xml /usr/local/grass84/gui/wxpython/xml/module_items.xml;

# Build the GDAL-GRASS plugin
RUN git clone --depth 1 -b 1.0.4 https://github.com/OSGeo/gdal-grass \
    && cd "gdal-grass" \
    && ./configure \
      --with-gdal=/usr/bin/gdal-config \
      --with-grass=/usr/local/grass84 \
    && make -j $NUMTHREADS \
    && make install -j $NUMTHREADS \
    && cd /src \
    && rm -rf "gdal-grass"

# Leave build stage
FROM grass_gis as grass_gis_final

# GRASS GIS specific
# allow work with MAPSETs that are not owned by current user
ENV GRASS_SKIP_MAPSET_OWNER_CHECK=1 \
    SHELL="/bin/bash" \
    # https://proj.org/usage/environmentvars.html#envvar-PROJ_NETWORK
    PROJ_NETWORK=ON \
    LC_ALL="en_US.UTF-8" \
    PYTHONPATH="/usr/local/grass/etc/python/:${PYTHONPATH}" \
    LD_LIBRARY_PATH="/usr/local/grass/lib:$LD_LIBRARY_PATH" \
    GDAL_DRIVER_PATH="/usr/lib64/gdalplugins"

# Determine Python version dynamically
RUN PYTHON_VERSION=$(python3 -c "import sys; print(f'python{sys.version_info.major}.{sys.version_info.minor}')") \
    && echo "export PYTHON_VERSION=$PYTHON_VERSION" >> /etc/profile.d/python_version.sh

# Copy GRASS GIS from build image
COPY --link --from=build /usr/local/bin/* /usr/local/bin/
COPY --link --from=build /usr/local/grass84 /usr/local/grass84/
COPY --link --from=build /src/site-packages /usr/local/lib64/python3.9/site-packages/
COPY --link --from=build /usr/lib64/gdalplugins /usr/lib64/gdalplugins

# Create generic GRASS GIS lib name regardless of version number
RUN ln -sf /usr/local/grass84 /usr/local/grass

# show GRASS GIS, PROJ, GDAL etc versions
RUN grass --tmp-project EPSG:4326 --exec g.version -rge && \
    python3 --version

WORKDIR /scripts

# enable GRASS GIS Python session support
## grass --config python-path
ENV PYTHONPATH "/usr/local/grass/etc/python:${PYTHONPATH}"
# enable GRASS GIS ctypes imports
## grass --config path
ENV LD_LIBRARY_PATH "/usr/local/grass/lib:$LD_LIBRARY_PATH"

WORKDIR /tmp
COPY docker/testdata/simple.laz .
WORKDIR /scripts
COPY docker/testdata/test_grass_session.py .
## run GRASS GIS python session and scan the test LAZ file
RUN python3 /scripts/test_grass_session.py
RUN rm -rf /tmp/grasstest_epsg_25832

WORKDIR /grassdb
VOLUME /grassdb

CMD ["$GRASSBIN", "--version"]
