# syntax=docker/dockerfile:1.8@sha256:d6d396f3780b1dd56a3acbc975f57bd2fc501989b50164c41387c42d04e780d0

# Note: This file must be kept in sync in ./Dockerfile and ./docker/ubuntu/Dockerfile.
#       Changes to this file must be copied over to the other file.

ARG GUI=without

FROM quay.io/condaforge/linux-anvil-x86_64:alma9 as common_start

LABEL authors="Carmen Tawalika,Markus Neteler,Anika Weinmann,Stefan Blumentrath"
LABEL maintainer="tawalika@mundialis.de,neteler@mundialis.de,weinmann@mundialis.de"

SHELL ["/bin/bash", "-c"]

WORKDIR /tmp

ARG GUI

# Todo: re-consider required dev packages for addons (~400MB in dev packages)
ARG GRASS_RUN_PACKAGES="bison \
    bzip2 \
    curl \
    flex \
    gcc \
    gcc-c++ \
    gdal \
    geos \
    proj \
    netcdf \
    git \
    cairo \
    libcurl-devel \
    fftw \
    fftw-devel \
    freetype \
    gdal-devel \
    gsl \
    libjpeg-turbo \
    jsoncpp-devel \
    file \
    file-libs \
    ncurses \
    openblas \
    openblas-devel \
    openjpeg2 \
    libomp \
    libomp-devel \
    geos-devel \
    PDAL \
    PDAL-devel \
    proj-devel \
    proj-data-north-america \
    postgresql-devel \
    gsl-devel \
    python3 \
    python3-devel \
    readline \
    sqlite \
    libtiff \
    libzstd \
    make \
    mesa-libGL \
    mesa-libGLU \
    moreutils \
    ncurses \
    sqlite \
    unzip \
    vim \
    wget \
    zip \
    zlib \
    "
ENV GRASS_RUN_PACKAGES=${GRASS_RUN_PACKAGES}

# Define build packages
ARG GRASS_BUILD_PACKAGES="cmake \
    bzip2-devel \
    cairo-devel \
    freetype-devel \
    zlib-devel \
    netcdf-devel \
    openjpeg2-devel \
    readline-devel \
    libjpeg-turbo-devel \
    sqlite-devel \
    libtiff-devel \
    libzstd-devel \
    ncurses-devel \
    mesa-libGL-devel \
    mesa-libGLU-devel \
    zlib-devel \
    "
ENV GRASS_BUILD_PACKAGES=${GRASS_BUILD_PACKAGES}

ARG GRASS_CONFIG="--with-cxx \
  --enable-largefile \
  --with-proj-share=/usr/share/proj \
  --with-gdal=/usr/bin/gdal-config \
  --with-geos \
  --with-sqlite \
  --with-cairo --with-cairo-ldflags=-lfontconfig \
  --with-freetype --with-freetype-includes=/usr/include/freetype2/ \
  --with-fftw \
  --with-postgres --with-postgres-includes=/usr/include/postgresql \
  --with-netcdf \
  --with-zstd \
  --with-bzlib \
  --with-pdal \
  --without-mysql \
  --with-blas \
  --with-lapack \
  --with-readline \
  --with-odbc \
  --with-openmp \
  "

ARG GRASS_PYTHON_PACKAGES="pip \
    setuptools \
    python-dateutil \
    python-magic \
    numpy \
    Pillow \
    ply \
    matplotlib \
    psycopg2 \
  "
ENV GRASS_PYTHON_PACKAGES=${GRASS_PYTHON_PACKAGES}


FROM common_start as grass_without_gui

ARG GRASS_CONFIG="${GRASS_CONFIG} --without-opengl"
ENV GRASS_CONFIG=${GRASS_CONFIG}

FROM common_start as grass_with_gui

ARG GRASS_RUN_PACKAGES="${GRASS_RUN_PACKAGES} adwaita-icon-theme \
  mesa-libGLU \
  gtk3 \
  libnotify \
  SDL2 \
  libXtst \
  librsvg2 \
  gettext \
  freeglut \
  gstreamer1-plugins-base \
  libjpeg-turbo \
  libpng \
  libSM \
  libtiff \
  webkit2gtk3 \
"

ARG GRASS_BUILD_PACKAGES="${GRASS_BUILD_PACKAGES} adwaita-icon-theme \
  mesa-libGL-devel \
  mesa-libGLU-devel \
  freeglut-devel \
  gstreamer1-plugins-base-devel \
  gtk3-devel \
  libjpeg-turbo-devel \
  libnotify-devel \
  libpng-devel \
  SDL2-devel \
  libSM-devel \
  libtiff-devel \
  webkit2gtk3-devel \
  libXtst-devel \
"

ARG GRASS_CONFIG="${GRASS_CONFIG} --with-opengl \
  --with-x \
  --with-nls \
  --with-readline \
  "
ARG GRASS_PYTHON_PACKAGES="${GRASS_PYTHON_PACKAGES} wxPython"
# If you do not use any Gnome Accessibility features, to suppress warning
# WARNING **: Couldn't connect to accessibility bus:
# execute programs with
ENV NO_AT_BRIDGE=1


FROM grass_${GUI}_gui as grass_gis
# Install EPEL and fetch packages
RUN dnf install -y epel-release \
    && dnf config-manager --set-enabled crb \
    && dnf update -y \
    && dnf install -y \
    $GRASS_RUN_PACKAGES \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# Set locale
RUN dnf install -y glibc-langpack-en \
    && localedef -i en_US -f UTF-8 en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

## fetch vertical datums for PDAL and store into PROJ dir
WORKDIR /src

# # Get datum grids
# # Currently using https://proj.org/en/9.3/usage/network.html#how-to-enable-network-capabilities
# FROM ubuntu:24.04 as datum_grids

# # See: https://github.com/OSGeo/PROJ-data
# RUN apt-get update \
#     && apt-get install  -y --no-install-recommends --no-install-suggests \
#     wget \
#     && apt-get clean all \
#     && rm -rf /var/lib/apt/lists/*

# WORKDIR /tmp
# RUN wget --no-check-certificate -r -l inf -A tif https://cdn.proj.org/

# Start build stage
FROM grass_gis as build

# Add build packages
RUN dnf install -y \
    $GRASS_BUILD_PACKAGES \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# Add pip and Python packages
RUN (echo "Install Python" \
    && wget https://bootstrap.pypa.io/pip/get-pip.py \
    && python3 get-pip.py \
    && rm -r get-pip.py \
    && mkdir -p /src/site-packages \
    && cd /src \
    && python3 -m pip install --no-cache-dir -t /src/site-packages --upgrade \
    $GRASS_PYTHON_PACKAGES \
    && rm -rf /root/.cache \
    && rm -rf /tmp/pip-* \
    )

# copy grass gis source
COPY . /src/grass_build/

WORKDIR /src/grass_build

# Set environmental variables for GRASS GIS compilation, without debug symbols
# Set gcc/g++ environmental variables for GRASS GIS compilation, without debug symbols
ENV MYCFLAGS "-O2 -std=gnu99 -m64"
ENV MYLDFLAGS "-s"
# CXX stuff:
ENV LD_LIBRARY_PATH "/usr/local/lib"
ENV LDFLAGS "$MYLDFLAGS"
ENV CFLAGS "$MYCFLAGS"
ENV CXXFLAGS "$MYCXXFLAGS"

# Configure compile and install GRASS GIS
ENV NUMTHREADS=4
RUN make distclean || echo "nothing to clean"
RUN ./configure $GRASS_CONFIG \
    && make -j $NUMTHREADS \
    && make install && ldconfig \
    &&  cp /usr/local/grass84/gui/wxpython/xml/module_items.xml module_items.xml; \
    rm -rf /usr/local/grass84/demolocation; \
    rm -rf /usr/local/grass84/fonts; \
    rm -rf /usr/local/grass84/gui; \
    rm -rf /usr/local/grass84/share; \
    mkdir -p /usr/local/grass84/gui/wxpython/xml/; \
    mv module_items.xml /usr/local/grass84/gui/wxpython/xml/module_items.xml;

# Build the GDAL-GRASS plugin
RUN git clone --depth 1 -b 1.0.4 https://github.com/OSGeo/gdal-grass \
    && cd "gdal-grass" \
    && ./configure \
      --with-gdal=/usr/bin/gdal-config \
      --with-grass=/usr/local/grass84 \
    && make -j $NUMTHREADS \
    && make install -j $NUMTHREADS \
    && cd /src \
    && rm -rf "gdal-grass"

# Leave build stage
FROM grass_gis as grass_gis_final

# GRASS GIS specific
# allow work with MAPSETs that are not owned by current user
ENV GRASS_SKIP_MAPSET_OWNER_CHECK=1 \
    SHELL="/bin/bash" \
    # https://proj.org/usage/environmentvars.html#envvar-PROJ_NETWORK
    PROJ_NETWORK=ON \
    LC_ALL="en_US.UTF-8" \
    PYTHONPATH="/usr/local/grass/etc/python/:${PYTHONPATH}" \
    LD_LIBRARY_PATH="/usr/local/grass/lib:$LD_LIBRARY_PATH" \
    GDAL_DRIVER_PATH="/usr/lib/gdalplugins"

# Copy GRASS GIS from build image
COPY --link --from=build /usr/local/bin/* /usr/local/bin/
COPY --link --from=build /usr/local/grass84 /usr/local/grass84/
COPY --link --from=build /src/site-packages /usr/lib/python3.10/
COPY --link --from=build /usr/lib/gdalplugins /usr/lib/gdalplugins
# COPY --link --from=datum_grids /tmp/cdn.proj.org/*.tif /usr/share/proj/

# Create generic GRASS GIS lib name regardless of version number
RUN ln -sf /usr/local/grass84 /usr/local/grass

# show GRASS GIS, PROJ, GDAL etc versions
RUN grass --tmp-project EPSG:4326 --exec g.version -rge && \
    pdal --version && \
    python --version

WORKDIR /scripts

# enable GRASS GIS Python session support
## grass --config python-path
ENV PYTHONPATH "/usr/local/grass/etc/python:${PYTHONPATH}"
# enable GRASS GIS ctypes imports
## grass --config path
ENV LD_LIBRARY_PATH "/usr/local/grass/lib:$LD_LIBRARY_PATH"

WORKDIR /tmp
COPY docker/testdata/simple.laz .
WORKDIR /scripts
COPY docker/testdata/test_grass_session.py .
## run GRASS GIS python session and scan the test LAZ file
RUN python /scripts/test_grass_session.py
RUN rm -rf /tmp/grasstest_epsg_25832
# test LAZ file
RUN grass --tmp-project EPSG:25832 --exec r.in.pdal input="/tmp/simple.laz" output="count_1" method="n" resolution=1 -g
WORKDIR /grassdb
VOLUME /grassdb

CMD ["$GRASSBIN", "--version"]
